### CLASSIFICATION

In [1]:
import numpy as np
import pandas as pd
import csv
import seaborn
from matplotlib import pyplot as plt
from matplotlib.ticker import StrMethodFormatter
plt.style.use('dark_background')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN

In [4]:
#subset for faster performance
mydata = pd.read_csv('accidents.csv', nrows=10000) 

##### Train Test Split     33-66

In [6]:
mydata=mydata.drop(['ID','Start_Lat','Start_Lng','End_Lat','Start_Time','End_Lng','End_Time','Precipitation(in)','Description','Number','Street','Side','City','Country','State','Zipcode','County','Timezone','Airport_Code','Weather_Timestamp','Temperature(F)','Wind_Chill(F)','Wind_Direction','Amenity','Bump','Crossing','Give_Way','Junction','Traffic_Calming','Traffic_Signal','No_Exit','Railway','Turning_Loop','Roundabout','Station','Stop','Sunrise_Sunset','Civil_Twilight','Nautical_Twilight','Astronomical_Twilight'],axis=1)

In [7]:
mydata=mydata.drop('Weather_Condition',axis=1)

In [8]:
mydata=mydata.dropna() 

In [9]:
myVal=mydata['Severity']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(mydata, myVal, test_size=0.33, random_state=42)

#### LOGISTIC REGRESSION

In [11]:
machine = LogisticRegression()

In [12]:
machine.fit(X_train,y_train)

C:\Users\konst\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
predictions = machine.predict(X_test)

In [14]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           2       1.00      1.00      1.00      2265
           3       1.00      1.00      1.00       315
           4       1.00      1.00      1.00       149

    accuracy                           1.00      2729
   macro avg       1.00      1.00      1.00      2729
weighted avg       1.00      1.00      1.00      2729



In [15]:
print(confusion_matrix(y_test,predictions))

[[2265    0    0]
 [   0  315    0]
 [   0    0  149]]


#### K_NEAREST

In [32]:
#may cause time error if you use the whole dataset

In [16]:
 machine = KNeighborsClassifier(n_neighbors = 15)

In [17]:
 machine.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [18]:
 predictions  = machine.predict(X_test)

In [19]:
 print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           2       0.85      1.00      0.92      2265
           3       0.32      0.05      0.09       315
           4       0.69      0.07      0.13       149

    accuracy                           0.84      2729
   macro avg       0.62      0.38      0.38      2729
weighted avg       0.78      0.84      0.78      2729



In [20]:
 print(confusion_matrix(y_test,predictions))

[[2262    0    3]
 [ 296   17    2]
 [ 102   36   11]]


#may cause time error if you use the whole dataset#### DECISION TREE

In [22]:
machine = DecisionTreeClassifier()

In [23]:
machine.fit(X_train,y_train)

DecisionTreeClassifier()

In [24]:
predictions = machine.predict(X_test)

In [25]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           2       1.00      1.00      1.00      2265
           3       1.00      1.00      1.00       315
           4       1.00      1.00      1.00       149

    accuracy                           1.00      2729
   macro avg       1.00      1.00      1.00      2729
weighted avg       1.00      1.00      1.00      2729



In [26]:
print(confusion_matrix(y_test,predictions))

[[2265    0    0]
 [   0  315    0]
 [   0    0  149]]


#### RANDOM FOREST

In [33]:
#may cause time error if you use the whole dataset

In [27]:
machine = RandomForestClassifier(n_estimators=100)

In [28]:
machine.fit(X_train, y_train)

RandomForestClassifier()

In [29]:
 predictions = machine.predict(X_test)

In [30]:
 print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           2       1.00      1.00      1.00      2265
           3       1.00      1.00      1.00       315
           4       1.00      1.00      1.00       149

    accuracy                           1.00      2729
   macro avg       1.00      1.00      1.00      2729
weighted avg       1.00      1.00      1.00      2729



In [31]:
 print(confusion_matrix(y_test,predictions))

[[2265    0    0]
 [   0  315    0]
 [   0    0  149]]


 #### SVM 

In [34]:
machine = SVC()

In [39]:
#may cause time error if you use the whole dataset

In [35]:
machine.fit(X_train,y_train)

SVC()

In [36]:
predictions = machine.predict(X_test)

In [37]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           2       0.83      1.00      0.91      2265
           3       0.00      0.00      0.00       315
           4       0.00      0.00      0.00       149

    accuracy                           0.83      2729
   macro avg       0.28      0.33      0.30      2729
weighted avg       0.69      0.83      0.75      2729



C:\Users\konst\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\konst\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\konst\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [38]:
print(confusion_matrix(y_test,predictions))

[[2265    0    0]
 [ 315    0    0]
 [ 149    0    0]]
